# This configuration file provides default values for the NEAR indexer.
# Values marked with "set_in_env" and any other settings can be overridden
# by environment variables using the format "INDEXER_{SECTION}_{KEY}"
# For example: INDEXER_DB_HOST=localhost will override db_host

# Database Configuration
db_host = "postgres"  # Docker service name for postgres
db_port = 5432

db_database = "postgres"
db_username = "postgres"
db_password = "postgres"

db_schema = "fastnear"
db_max_connections = 10

# Indexer Configuration
start_block = 183500000 # first proposal block 199579301, jan 1st block 183500000
batch_size = 10
poll_interval = 1
max_retries = 3
retry_delay = 5
num_threads = 64

# NEAR API Configuration
api_url = "https://rpc.testnet.nearblocks.io"
# api_auth_token = set_in_env
api_chain_id = "testnet"
api_finality = "final"

# Other
venear_contracts = [
    "r-1745564650.testnet",
    "r-1746683627.testnet", 
    "r-1748895584.testnet"
]
log_level = "info"
app_version = "v1.0.0"