services:
  near-sink-sql:
    container_name: near-sink-sql
    platform: linux/amd64
    build: .
    environment:
      ENDPOINT: ${ENDPOINT}
      DSN: ${DSN}
      SUBSTREAMS_API_KEY: ${SUBSTREAMS_API_KEY}
