name: Deploy Dev

on:
  workflow_dispatch: # This allows the workflow to be manually triggered from the GitHub UI
  push:
    branches:
      - main

env:
  PROJECT_NUMBER: "158107670134"
  SERVICE_ACCOUNT_EMAIL: "github-actions@agora-near.iam.gserviceaccount.com"
  PROJECT_ID: "agora-near"
  REGION: "us-west1"
  DOCKER_IMAGE: "us-west1-docker.pkg.dev/agora-near/indexer/near-sink-service"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud using OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-identity-pool/providers/github
          service_account: ${{env.SERVICE_ACCOUNT_EMAIL}}

      - name: Configure gcloud
        run: gcloud config set project ${{env.PROJECT_ID}}

      - name: Login to Artifact Registry
        run: gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev

      - name: Generate .env from GCP Secret Manager
        run: |
          DB_USER=$(gcloud secrets versions access latest --secret=DATABASE_USER)
          DB_PASS=$(gcloud secrets versions access latest --secret=DATABASE_PASSWORD)
          PINAX_KEY=$(gcloud secrets versions access latest --secret=PINAX_API_KEY)

          cat <<EOF > .env
          DSN=postgres://${DB_USER}:${DB_PASS}@10.0.0.3:5432/postgres?sslmode=disable
          ENDPOINT=neartest.substreams.pinax.network:443
          SUBSTREAMS_API_KEY=${PINAX_KEY}
          EOF

      - name: Build Docker image
        run: docker build -t ${{env.DOCKER_IMAGE}} .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{env.DOCKER_IMAGE}}
