name: Deploy HOS Dev

on:
  workflow_dispatch: # This allows the workflow to be manually triggered from the GitHub UI

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: hos-development

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud using OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{vars.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-identity-pool/providers/github
          service_account: ${{vars.GCP_SA_EMAIL}}

      - name: Configure gcloud
        run: gcloud config set project ${{vars.GCP_PROJECT_ID}}

      - name: Login to Artifact Registry
        run: gcloud auth configure-docker ${{vars.GCP_REGION}}-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t ${{vars.GCP_DOCKER_IMAGE}} .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{vars.GCP_DOCKER_IMAGE}}

      - name: Docker cleanup on VM
        run: |
          gcloud compute ssh ${{vars.GCP_VM_NAME}} \
            --zone=${{vars.GCP_REGION}}-a \
            --project=${{vars.GCP_PROJECT_ID}} \
            --command="sudo docker system prune --all --force --volumes"

      - name: Restart Compute Engine VM
        run: |
          gcloud compute instances reset ${{vars.GCP_VM_NAME}} \
            --zone=${{vars.GCP_REGION}}-a \
            --project=${{vars.GCP_PROJECT_ID}}
